### ISSUE TITLE
Should Ecto.ChangeError be handled by plug.ex?

### ISSUE THREAD

**Issue by aselder** [phoenixframework/phoenix_ecto#131]
Bad user input can result in Ecto.ChangeError which isn't handled by the error handling in plug.ex

I'll like to propose that Ecto.ChangeError be mapped to return a 400 Bad Request or 422 Unprocessable Entity.

If people are agreeable, I'm happy to put together the PR.

**Comment by josevalim** [comment]
We have just recently changed the project to no longer handle Ecto changes errors as 422, because those are intentionally not logged, causing errors to be silenced.

Given that you would not want to raise those on HTML projects, since you usually have to re-render, and given that the fallback controller is a better abstraction for APIs, I believe we should not add this and similar behavior back. :)

**Comment by juantascon** [comment]
@josevalim what is the proper way to handle InvalidChangesetError after say a `Repo.insert!()` call fails? should I just use `Repo.insert()` instead and rely on FallbackController? using `Repo.insert!()` has allowed me to write cleaner code using the pipe operator.

**Comment by josevalim** [comment]
> should I just use Repo.insert() instead and rely on FallbackController?

Yes.

**Comment by josevalim** [comment]
Closing per the above.
